services:
  - type: web
    name: calli-poke-mcp
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: calli-poke-mcp
          property: port
      - key: VAPI_API_KEY
        sync: false
      - key: VAPI_PHONE_ID
        sync: false
      - key: VAPI_ASSISTANT_ID
        sync: false
      - key: POKE_API_KEY
        sync: false